### ISSUE TITLE
Publish this as a package?

### ISSUE THREAD

**Issue by srihariash999** [dutrieuc/gpodder_client#1]
Hi @dutrieuc  I see you have done quite some work on this dart lib, are you planning to publish this on pub.dev ?

**Comment by dutrieuc** [comment]
Hey @srihariash999, yeah I can take some time to do it.
That being said, I don't know if it makes a lot of sense since I moved one to other stuff for now and I don't think it's very usable yet (but very open to contributions if you need to add some features).

**Comment by srihariash999** [comment]
Makes sense, Thanks.
